services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:9090/shop_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=shopForExam
    depends_on:
      - db
    networks:
      - shop-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=shop_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=shopForExam
    ports:
      - "9090:9090"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shop-network

networks:
  shop-network:
    driver: bridge

volumes:
  postgres_data: